version: '3.9'

services:
  web:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:123456@db:5432/expomusic_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
  
  db:
    image: postgres:17.2
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=expomusic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d base_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  

  frontend:
    build: ./frontend
    container_name: vue_app
    ports:
      - "5500:5500"  # !!! ВНИМАНИЕ: Порт может измениться
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Избегаем перезаписи node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - web  # Зависит от сервера (FastAPI)

volumes:
  postgres_data: